#ifndef CHARGEN_VERSION_NUMBER
#define CHARGEN_VERSION_NUMBER 0.0
#endif


#define IDD_VERSION 150
#ifndef IDM_CHARGEN_MENU

#define IDM_CHARGEN_MENU 1980

#define IDC_NEW_SHEET   1981
#define IDC_OPEN_SHEET  1982
#define IDC_SAVE_AS     1983
#define IDC_SAVE_CURRENT 1984
#define IDC_CLOSE_SHEET 1985
#define IDC_QUIT_PROGRAM 1986
#define IDC_COPY_MENU   1987
#define IDC_PASTE_MENU 1988
#define IDC_CHARGEN_HELP        1989
#define IDC_VERSION     1990

#endif /* IDM_CHARGEN_MENU */
